<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'code' => 'FRN-001',
                'name' => 'Cosumar S.A.',
                'contact' => 'Mohammed Alami',
                'phone' => '+212 5 22 84 00 00',
                'email' => 'commercial@cosumar.co.ma',
                'city' => 'Casablanca',
                'address' => '8 Rue El Abbès, Mers Sultan',
                'ice' => '001045720000056',
                'rc' => '55431',
                'products_count' => 4,
                'last_order' => '02 Oct 2026',
                'total_purchases' => 1240500.00,
                'status' => 'Actif',
                'categories' => ['Sucre', 'Dérivés sucriers'],
                'payment_terms' => '60 jours fin de mois',
                'lead_time_days' => 5,
            ],
            [
                'code' => 'FRN-002',
                'name' => 'Lesieur Cristal',
                'contact' => 'Karim Benali',
                'phone' => '+212 5 22 36 36 36',
                'email' => 'ventes@lesieur.ma',
                'city' => 'Casablanca',
                'address' => 'Route de Rabat, Ain Sebaâ',
                'ice' => '003284100000012',
                'rc' => '68920',
                'products_count' => 6,
                'last_order' => '29 Sep 2026',
                'total_purchases' => 2180000.00,
                'status' => 'Actif',
                'categories' => ['Huiles végétales', 'Savons'],
                'payment_terms' => '45 jours date facture',
                'lead_time_days' => 3,
            ],
            [
                'code' => 'FRN-003',
                'name' => 'Minoterie Tazi & Fils',
                'contact' => 'Hassan Tazi',
                'phone' => '+212 5 23 40 12 34',
                'email' => 'htazi@minotazi.ma',
                'city' => 'Berrechid',
                'address' => 'Zone Industrielle Berrechid, Lot 12',
                'ice' => '008174220000041',
                'rc' => '34567',
                'products_count' => 3,
                'last_order' => '25 Sep 2026',
                'total_purchases' => 876300.00,
                'status' => 'Actif',
                'categories' => ['Farines', 'Semoules'],
                'payment_terms' => '30 jours date facture',
                'lead_time_days' => 7,
            ],
            [
                'code' => 'FRN-004',
                'name' => 'Salines du Gharb',
                'contact' => 'Fatima Bennani',
                'phone' => '+212 5 37 61 80 00',
                'email' => 'contact@salines-gharb.ma',
                'city' => 'Kenitra',
                'address' => 'Route de la Mer, Kenitra',
                'ice' => '006429800000078',
                'rc' => '22301',
                'products_count' => 2,
                'last_order' => '18 Sep 2026',
                'total_purchases' => 345800.00,
                'status' => 'Actif',
                'categories' => ['Sel industriel', 'Sel alimentaire'],
                'payment_terms' => '30 jours date facture',
                'lead_time_days' => 10,
            ],
            [
                'code' => 'FRN-005',
                'name' => 'Rizerie El Ouahda',
                'contact' => 'Omar Cherkaoui',
                'phone' => '+212 6 61 23 45 67',
                'email' => 'riz-elouahda@gmail.com',
                'city' => 'Mohammedia',
                'address' => 'Port de Mohammedia, Hangar 7',
                'ice' => '007834100000090',
                'rc' => '89012',
                'products_count' => 2,
                'last_order' => '10 Sep 2026',
                'total_purchases' => 490200.00,
                'status' => 'Inactif',
                'categories' => ['Riz', 'Légumineuses'],
                'payment_terms' => '60 jours fin de mois',
                'lead_time_days' => 14,
            ],
            [
                'code' => 'FRN-006',
                'name' => 'Import Légumes Sec SARL',
                'contact' => 'Youssef Mansouri',
                'phone' => '+212 5 22 72 00 01',
                'email' => 'y.mansouri@ils-sarl.ma',
                'city' => 'Casablanca',
                'address' => 'Derb Omar, Bloc C',
                'ice' => '002891000000033',
                'rc' => '44123',
                'products_count' => 5,
                'last_order' => '05 Aug 2026',
                'total_purchases' => 184600.00,
                'status' => 'Suspendu',
                'categories' => ['Lentilles', 'Pois chiches', 'Haricots'],
                'payment_terms' => 'Comptant livraison',
                'lead_time_days' => 21,
            ],
            [
                'code' => 'FRN-007',
                'name' => 'Ingelec Maroc',
                'contact' => 'Samir Berrada',
                'phone' => '+212 5 22 35 44 00',
                'email' => 'contact@ingelec.com',
                'city' => 'Casablanca',
                'address' => '323 Bd Moulay Ismail, Roches Noires',
                'ice' => '001584930000017',
                'rc' => '12894',
                'products_count' => 8,
                'last_order' => '04 Oct 2026',
                'total_purchases' => 1650000.00,
                'status' => 'Actif',
                'categories' => ['Appareillage électrique', 'Câblage', 'Disjoncteurs'],
                'payment_terms' => '45 jours fin de mois',
                'lead_time_days' => 4,
            ],
            [
                'code' => 'FRN-008',
                'name' => 'Dolidol Métallurgie & Quincaillerie',
                'contact' => 'Adil Naciri',
                'phone' => '+212 5 22 76 50 00',
                'email' => 'quincaillerie@dolidol.ma',
                'city' => 'Casablanca',
                'address' => 'Zone Industrielle Sidi Bernoussi',
                'ice' => '002948170000095',
                'rc' => '38721',
                'products_count' => 7,
                'last_order' => '01 Oct 2026',
                'total_purchases' => 920400.00,
                'status' => 'Actif',
                'categories' => ['Charnières', 'Visserie', 'Accessoires métalliques'],
                'payment_terms' => '30 jours date facture',
                'lead_time_days' => 6,
            ],
        ];

        foreach ($suppliers as $item) {
            Supplier::updateOrCreate(
                ['code' => $item['code']],
                $item
            );
        }

        $this->command?->info('SupplierSeeder: 8 fournisseurs marocains enregistrés.');
    }
}
